### Register a new user
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "TestBoy",
  "email": "testboy@gmail.com",
  "password": "1234" 
}
### Login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "testboy@gmail.com",
  "password": "1234" 
}

### Create a new task
POST http://localhost:3000/api/tasks/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjMGYxYWEyYTA2YWI1NjUxYTFiMTYiLCJ1c2VybmFtZSI6IlRlc3RCb3kiLCJpYXQiOjE3NDY2Njk0NDcsImV4cCI6MTc0NjY3MzA0N30.vApaATakfCwTBCR1Q0KfdOPs-Lh0m0dlaOzBmrR5bKc

{
  "title": "Test 2",
  "description": "Description of the test for task 2"
}

### Get all tasks of user
GET http://localhost:3000/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjMGYxYWEyYTA2YWI1NjUxYTFiMTYiLCJ1c2VybmFtZSI6IlRlc3RCb3kiLCJpYXQiOjE3NDY2Njk0NDcsImV4cCI6MTc0NjY3MzA0N30.vApaATakfCwTBCR1Q0KfdOPs-Lh0m0dlaOzBmrR5bKc

### Get details of one task
GET http://localhost:3000/api/tasks/681c0ffba2a06ab5651a1b1a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFjMGYxYWEyYTA2YWI1NjUxYTFiMTYiLCJ1c2VybmFtZSI6IlRlc3RCb3kiLCJpYXQiOjE3NDY2Njk0NDcsImV4cCI6MTc0NjY3MzA0N30.vApaATakfCwTBCR1Q0KfdOPs-Lh0m0dlaOzBmrR5bKc