### Get all users
GET http://localhost:3000/api/users

### Get all tasks of a user
GET http://localhost:3000/api/users/6818f25524e36749ab713d27/tasks

### Post a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "userName": "TestBoy",
  "email": "pato@gmail.com",
  "password": "12345"
}

### Login as existing user
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "pato@gmail.com",
  "password": "1234"
}

### Post a new task
POST http://localhost:3000/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IlBhdHJpY2lvIiwiaWQiOiI2ODE4ZjI1NTI0ZTM2NzQ5YWI3MTNkMjciLCJpYXQiOjE3NDY0ODM2ODksImV4cCI6MTc0NjQ4NzI4OX0.gsvSxEfVn5uXNCMwK2HdVIVM3oIKcQ0l3iI85H-USpc

{
  "title": "Test 9",
  "description": "This is a description"
}